on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
jobs:
  playwrighttests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x.x

      - name: Build tests code
        run: cd Test && dotnet build && pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps

      - name: Build and run Web API
        run: cd API && dotnet run & echo "API_PID=$!" >> $GITHUB_ENV
        env:
          pgconn: ${{secrets.PGCONN}}

      - name: Run tests
        run: cd Test && sleep 60 && dotnet test
        env:
          pgconn: ${{secrets.PGCONN}}

      - name: Shutdown
        run: kill $API_PID